# Generated by Django 4.0.3 on 2022-04-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date_pub',
            new_name='pub_date',
        ),
    ]
